name: Maven CI/CD

on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build project with Maven
    - run: mkdir test test1 test2 && cd test
    - run: cd test1 
    - run: cd test2
      
